/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => main_default
});
module.exports = __toCommonJS(main_exports);

// src/service/kebabCase.ts
function kebabCase(str) {
  return str.replace(/[^a-zA-Z0-9 ]/g, " ").replace(/\s+/g, "-").toLocaleLowerCase();
}

// src/OllamaGlobal.ts
var import_obsidian2 = require("obsidian");

// src/OllamaSettingTab.ts
var import_obsidian = require("obsidian");

// src/data/defaultSettings.ts
var DEFAULT_SETTINGS = {
  ollamaUrl: "http://localhost:11434",
  globalModel: "llama2",
  storyModeEnabled: true,
  storyModePrompt: "You are a storyteller in the tradition of George R.R. Martin and J.R.R. Tolkien. Your prose is rich, evocative, and measured. You favour a third-person limited point of view, with deep attention to sensory details, inner conflict, and the weight of history. Dialogue is sharp and reveals character. You avoid modern slang and anachronisms. When you describe a scene, you linger on the light, the cold, the smell of rain on stone, the creak of leather, the unspoken tension between two people. Your tone is epic but intimate, intriguing and slightly somber. You never rush. You build atmosphere.",
  systemPrompt: "",
  commands: [
    {
      name: "Summarize selection",
      prompt: "Act as a writer. Summarize the text in a view sentences highlighting the key takeaways. Output only the text and nothing else, do not chat, no preamble, get to the point."
    },
    {
      name: "Explain selection",
      prompt: "Act as a writer. Explain the text in simple and concise terms keeping the same meaning. Output only the text and nothing else, do not chat, no preamble, get to the point."
    },
    {
      name: "Expand selection",
      prompt: "Act as a writer. Expand the text by adding more details while keeping the same meaning. Output only the text and nothing else, do not chat, no preamble, get to the point."
    },
    {
      name: "Rewrite the selection",
      prompt: "Act as a writer. Rewrite the text while preserving the meaning, clarity, and style. Output only the rewritten text and nothing else, do not chat, no preamble."
    },
    {
      name: "Continue the story",
      prompt: "You are a fiction writer. Continue the story from the provided text. Write the next part seamlessly. Output only the continuation and nothing else, do not chat, no preamble."
    },
    {
      name: "Generate character description",
      prompt: "You are a fiction writer. Based on the text, generate a detailed description of a character mentioned. Output only the description and nothing else."
    },
    {
      name: "Summarize left panel",
      prompt: "Act as a writer. Summarize the text in a view sentences highlighting the key takeaways. Output only the text and nothing else, do not chat, no preamble, get to the point.",
      paneMode: "left-right"
    },
    {
      name: "Explain left panel",
      prompt: "Act as a writer. Explain the text in simple and concise terms keeping the same meaning. Output only the text and nothing else, do not chat, no preamble, get to the point.",
      paneMode: "left-right"
    },
    {
      name: "Expand left panel",
      prompt: "Act as a writer. Expand the text by adding more details while keeping the same meaning. Output only the text and nothing else, do not chat, no preamble, get to the point.",
      paneMode: "left-right"
    },
    {
      name: "Rewrite left panel",
      prompt: "Act as a writer. Rewrite the text while preserving the meaning, clarity, and style. Output only the rewritten text and nothing else, do not chat, no preamble.",
      paneMode: "left-right"
    },
    {
      name: "Rewrite left panel (casual)",
      prompt: "Act as a writer. Rewrite the text in a more casual style while keeping the same meaning. Output only the text and nothing else, do not chat, no preamble, get to the point.",
      paneMode: "left-right"
    },
    {
      name: "Continue the story from left panel",
      prompt: "You are a fiction writer. Continue the story from the provided text. Write the next part seamlessly. Output only the continuation and nothing else, do not chat, no preamble.",
      paneMode: "left-right"
    },
    {
      name: "Generate character description from left panel",
      prompt: "You are a fiction writer. Based on the text, generate a detailed description of a character mentioned. Output only the description and nothing else.",
      paneMode: "left-right"
    },
    {
      name: "Rewrite selection (formal)",
      prompt: "Act as a writer. Rewrite the text in a more formal style while keeping the same meaning. Output only the text and nothing else, do not chat, no preamble, get to the point."
    },
    {
      name: "Rewrite selection (casual)",
      prompt: "Act as a writer. Rewrite the text in a more casual style while keeping the same meaning. Output only the text and nothing else, do not chat, no preamble, get to the point."
    },
    {
      name: "Rewrite selection (active voice)",
      prompt: "Act as a writer. Rewrite the text in with an active voice while keeping the same meaning. Output only the text and nothing else, do not chat, no preamble, get to the point."
    },
    {
      name: "Rewrite selection (bullet points)",
      prompt: "Act as a writer. Rewrite the text into bullet points while keeping the same meaning. Output only the text and nothing else, do not chat, no preamble, get to the point."
    },
    {
      name: "Caption selection",
      prompt: "Act as a writer. Create only one single heading for the whole text that is giving a good understanding of what the reader can expect. Output only the caption and nothing else, do not chat, no preamble, get to the point. Your format should be ## Caption."
    }
  ]
};

// src/OllamaSettingTab.ts
var OllamaSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Ollama URL").setDesc("URL of the Ollama server (e.g. http://localhost:11434)").addText(
      (text) => text.setPlaceholder("http://localhost:11434").setValue(this.plugin.settings.ollamaUrl).onChange(async (value) => {
        this.plugin.settings.ollamaUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Global Model").setDesc("Name of the Ollama model to use for all commands").addText(
      (text) => text.setPlaceholder("llama2").setValue(this.plugin.settings.globalModel).onChange(async (value) => {
        this.plugin.settings.globalModel = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Story Mode").setDesc("Use the dedicated story mode prompt for all commands").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.storyModeEnabled).onChange(async (value) => {
        this.plugin.settings.storyModeEnabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Story Mode Prompt").setDesc("Story mode system prompt used when Story Mode is enabled").addTextArea((text) => {
      text.setPlaceholder(
        "Enter the story mode prompt used before every command prompt."
      ).setValue(this.plugin.settings.storyModePrompt).onChange(async (value) => {
        this.plugin.settings.storyModePrompt = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Custom System Prompt").setDesc(
      "Optional custom system prompt used when Story Mode is disabled"
    ).addTextArea((text) => {
      text.setPlaceholder(
        "Enter a custom system prompt for commands when Story Mode is off."
      ).setValue(this.plugin.settings.systemPrompt).onChange(async (value) => {
        this.plugin.settings.systemPrompt = value;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "Commands" });
    const newCommand = {
      name: "",
      prompt: "",
      temperature: void 0
    };
    new import_obsidian.Setting(containerEl).setName("New command name").addText((text) => {
      text.setPlaceholder("e.g. Summarize selection");
      text.onChange(async (value) => {
        newCommand.name = value;
      });
    });
    new import_obsidian.Setting(containerEl).setName("New command prompt").addTextArea((text) => {
      text.setPlaceholder(
        "e.g. Act as a writer. Summarize the text in a view sentences highlighting the key takeaways. Output only the text and nothing else, do not chat, no preamble, get to the point."
      );
      text.onChange(async (value) => {
        newCommand.prompt = value;
      });
    });
    new import_obsidian.Setting(containerEl).setName("New command temperature").addSlider((slider) => {
      slider.setLimits(0, 1, 0.01);
      slider.setValue(0.2);
      slider.onChange(async (value) => {
        newCommand.temperature = value;
      });
    });
    new import_obsidian.Setting(containerEl).setDesc("This requires a reload of obsidian to take effect.").addButton(
      (button) => button.setButtonText("Add Command").onClick(async () => {
        if (!newCommand.name) {
          new import_obsidian.Notice("Please enter a name for the command.");
          return;
        }
        if (this.plugin.settings.commands.find(
          (command) => command.name === newCommand.name
        )) {
          new import_obsidian.Notice(
            `A command with the name "${newCommand.name}" already exists.`
          );
          return;
        }
        if (!newCommand.prompt) {
          new import_obsidian.Notice("Please enter a prompt for the command.");
          return;
        }
        this.plugin.settings.commands.push(newCommand);
        await this.plugin.saveSettings();
        this.display();
      })
    );
    containerEl.createEl("h4", { text: "Existing Commands" });
    this.plugin.settings.commands.forEach((command) => {
      new import_obsidian.Setting(containerEl).setName(command.name).setDesc(`${command.prompt}`).addButton(
        (button) => button.setButtonText("Remove").onClick(async () => {
          this.plugin.settings.commands = this.plugin.settings.commands.filter(
            (c) => c.name !== command.name
          );
          await this.plugin.saveSettings();
          this.display();
        })
      );
    });
    containerEl.createEl("h4", { text: "Reset Commands" });
    new import_obsidian.Setting(containerEl).setName("Update Commands").setDesc(
      "Update commands to the default commands. This cannot be undone and will overwrite some commands by matching names. This requires a reload of obsidian to take effect."
    ).addButton((button) => {
      button.setWarning();
      return button.setButtonText("Update").onClick(async () => {
        DEFAULT_SETTINGS.commands.forEach((command) => {
          const existingCommand = this.plugin.settings.commands.find(
            (c) => c.name === command.name
          );
          if (existingCommand) {
            existingCommand.prompt = command.prompt;
            existingCommand.temperature = command.temperature;
          } else {
            this.plugin.settings.commands.push(command);
          }
        });
        await this.plugin.saveSettings();
        this.display();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Reset Commands").setDesc(
      "Reset all commands to the default commands. This cannot be undone and will delete all your custom commands. This requires a reload of obsidian to take effect."
    ).addButton((button) => {
      button.setWarning();
      return button.setButtonText("Reset").onClick(async () => {
        this.plugin.settings.commands = DEFAULT_SETTINGS.commands;
        await this.plugin.saveSettings();
        this.display();
      });
    });
  }
};

// src/OllamaGlobal.ts
var OllamaGlobal = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.addPromptCommands();
    this.addSettingTab(new OllamaSettingTab(this.app, this));
  }
  addPromptCommands() {
    this.settings.commands.forEach((command) => {
      this.addCommand({
        id: kebabCase(command.name),
        name: command.name,
        editorCallback: (editor) => {
          const usePanePair = command.paneMode === "left-right";
          let sourceEditor = editor;
          let targetEditor = editor;
          if (usePanePair) {
            const markdownLeaves = this.app.workspace.getLeavesOfType("markdown").filter((leaf) => leaf.view instanceof import_obsidian2.MarkdownView);
            if (markdownLeaves.length < 2) {
              new import_obsidian2.Notice(
                "Open two markdown panes side by side to use this command."
              );
              return;
            }
            sourceEditor = markdownLeaves[0].view.editor;
            targetEditor = markdownLeaves[1].view.editor;
          }
          const selection = sourceEditor.getSelection();
          const text = selection ? selection : sourceEditor.getValue();
          const cursorPosition = targetEditor.getCursor();
          targetEditor.replaceRange("\u270D\uFE0F", cursorPosition);
          const systemPrompt = this.settings.storyModeEnabled ? this.settings.storyModePrompt : this.settings.systemPrompt;
          const prompt = [systemPrompt, command.prompt, text].filter((part) => part && part.length > 0).join("\n\n");
          (0, import_obsidian2.requestUrl)({
            method: "POST",
            url: `${this.settings.ollamaUrl}/api/generate`,
            body: JSON.stringify({
              prompt,
              model: this.settings.globalModel,
              options: {
                temperature: command.temperature || 0.2
              }
            })
          }).then((response) => {
            const steps = response.text.split("\n").filter((step) => step && step.length > 0).map((step) => JSON.parse(step));
            targetEditor.replaceRange(
              steps.map((step) => step.response).join("").trim(),
              cursorPosition,
              {
                ch: cursorPosition.ch + 1,
                line: cursorPosition.line
              }
            );
          }).catch((error) => {
            new import_obsidian2.Notice(`Error while generating text: ${error.message}`);
            targetEditor.replaceRange("", cursorPosition, {
              ch: cursorPosition.ch + 1,
              line: cursorPosition.line
            });
          });
        }
      });
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};

// src/main.ts
var main_default = OllamaGlobal;
